networks:
  verbal:
    driver: bridge

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    networks:
      - verbal
    ports:
      - "4180:4180"
    volumes:
      - ./outside/oauth2-proxy.cfg:/etc/oauth2-proxy.cfg
      - ./outside/authenticated-emails:/etc/authenticated-emails
      - ./assets/logo.png:/var/verbal-logo.png
    env_file:
      - ./outside/.env
    command: --config=/etc/oauth2-proxy.cfg

  outside:
    build: ./outside
    networks:
      - verbal
    ports:
      - "3000:3000"

  inside:
    build: ./inside
    networks:
      - verbal
    ports:
      - "8000:8000"
    env_file:
      - ./inside/.env
    command: --server.baseUrlPath=/verbal

  inside-staging:
    build: ./inside
    networks:
      - verbal
    volumes:
      - ./data/staging:/data
    env_file:
      - ./inside/.env
    command: --server.baseUrlPath=/verbal-staging
