networks:
  verbal:
    driver: bridge

services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    networks:
      - verbal
    ports:
      - "4180:4180"
    volumes:
      - ./oauth2-proxy/authenticated-emails.txt:/etc/authenticated-emails.txt
      - ./assets/logo.png:/etc/verbal-logo.png
    env_file:
      - ./oauth2-proxy/config.env
      - ./oauth2-proxy/.env

  # manager:
  #   build: ./manager
  #   networks:
  #     - verbal
  #   volumes:
  #     - ./outside:/app
  #     - ./data:/data

  verbal:
    build: ./app
    networks:
      - verbal
    volumes:
      - .:/verbal
    env_file:
      - ./app/.env
